# Generated by Django 5.1.4 on 2024-12-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del equipo')),
                ('referencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Referencia del equipo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del equipo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de serie')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad en inventario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_entrada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('en_mantenimiento', 'En Mantenimiento'), ('retirado', 'Retirado')], default='disponible', max_length=20, null=True, verbose_name='Estado del equipo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='inventario.equipomaterial')),
            ],
        ),
    ]
