# Generated by Django 5.1.4 on 2024-12-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='inventario.factura', verbose_name='Factura relacionada'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Actividad'),
        ),
    ]
