# Generated by Django 5.1.4 on 2024-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_reporte_contenido_reporte_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='producto',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='filtro',
            field=models.CharField(choices=[('facturas', 'Facturas'), ('productos', 'Productos'), ('categorias', 'Categorías'), ('usuarios', 'Usuarios')], default='01-01-2024', max_length=50, verbose_name='Filtro de Datos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('general', 'Reporte General')], default='general', max_length=50, verbose_name='Tipo de Reporte'),
        ),
    ]
