# Generated by Django 5.1.4 on 2024-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_reporte_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('general', 'Reporte General'), ('personalizado', 'Reporte Personalizado'), ('estadistico', 'Reporte Estadístico'), ('operativo', 'Reporte Operativo'), ('financiero', 'Reporte Financiero')], default='general', max_length=50, verbose_name='Tipo de Reporte'),
        ),
    ]
