# Generated by Django 5.1.4 on 2024-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_reporte_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomaterial',
            name='estado',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('en_mantenimiento', 'En Mantenimiento'), ('retirado', 'Retirado')], default='disponible', max_length=20, null=True, verbose_name='Estado del equipo'),
        ),
    ]
