# Generated by Django 5.1.4 on 2024-12-26 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_equipomaterial_estado'),
    ]

    operations = [
    migrations.AlterField(
        model_name='equipomaterial',
        name='categoria',
        field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        preserve_default=False,
    ),
]

