# Generated by Django 5.1.4 on 2024-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_equipomaterial_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomaterial',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie'),
        ),
    ]
