# Generated by Django 5.1.4 on 2024-12-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_equipomaterial_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomaterial',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('retirado', 'Retirado')], default='disponible', max_length=20, verbose_name='Estado del equipo'),
        ),
    ]
