# Generated by Django 5.1.4 on 2024-12-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_equipomaterial_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='producto',
            new_name='EquipoMaterial',
        ),
    ]
