# Generated by Django 5.1.4 on 2024-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_rename_producto_mantenimiento_equipomaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='EquipoMaterial',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='equipomaterial',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_mantenimiento', 'En Mantenimiento'), ('retirado', 'Retirado')], default='disponible', max_length=20, verbose_name='Estado del equipo'),
        ),
    ]
