# Generated by Django 5.1.4 on 2024-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_rename_equipomaterial_mantenimiento_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomaterial',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
