# Generated by Django 5.1.4 on 2024-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_equipomaterial_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='filtro',
            field=models.CharField(choices=[('facturas', 'Facturas'), ('productos', 'Productos'), ('categorias', 'Categorías'), ('usuarios', 'Usuarios'), ('actividades', 'Actividades'), ('mantenimientos', 'Mantenimientos')], max_length=50, verbose_name='Filtro de Datos'),
        ),
    ]
