# Generated by Django 5.1.4 on 2024-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_reporte_filtro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default='2024-12-01', verbose_name='Fecha de Inicio del Resumen')),
                ('fecha_fin', models.DateField(default='2024-12-31', verbose_name='Fecha de Fin del Resumen')),
            ],
        ),
    ]
