# Generated by Django 5.1.4 on 2024-12-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_equipomaterial_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomaterial',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        ),
    ]
