# Generated by Django 5.1.4 on 2024-12-29 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_alter_equipomaterial_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='resumen',
            name='fecha_hoy',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
