# Generated by Django 5.1.4 on 2025-01-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_remove_resumen_fecha_fin_remove_resumen_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_hoy',
        ),
    ]
