# Generated by Django 5.1.4 on 2024-12-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_remove_resumen_fecha_fin_remove_resumen_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='resumen',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
