# Generated by Django 5.1.4 on 2025-01-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_resumen_fecha_fin_resumen_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_inicio',
        ),
    ]
