# Generated by Django 5.1.4 on 2025-01-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_remove_resumen_fecha_fin_remove_resumen_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='fecha_hoy',
        ),
    ]
