# Generated by Django 5.1.4 on 2025-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_remove_resumen_fecha_hoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='unico',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name='resumen',
            constraint=models.UniqueConstraint(fields=('unico',), name='unique_resumen_constraint'),
        ),
    ]
