# Generated by Django 5.1.4 on 2025-01-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_resumen_unico_resumen_unique_resumen_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resumen',
            name='unique_resumen_constraint',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='unico',
        ),
    ]
