# Generated by Django 5.1.4 on 2025-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_remove_resumen_unique_resumen_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='filtro',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('general', 'Reporte General'), ('stock', 'Reporte de Stock'), ('factura', 'Reporte de Facturas'), ('actividades', 'Reporte de Actividades')], max_length=50, verbose_name='Tipo de Reporte'),
        ),
    ]
