# Generated by Django 5.1.4 on 2025-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_remove_reporte_filtro_alter_reporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='compania_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía del Cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(default='cliente desconocido', max_length=100, verbose_name='Nombre del Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
