# Generated by Django 5.1.4 on 2025-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_factura_barrio_factura_compania_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='factura',
        ),
        migrations.AddField(
            model_name='actividad',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('categoria', 'Categoría'), ('producto', 'Producto'), ('factura', 'Factura'), ('pedido', 'Pedido'), ('mantenimiento', 'Mantenimiento'), ('resumen', 'Resumen'), ('reporte', 'Reporte')], max_length=50, verbose_name='Tipo de Actividad'),
        ),
    ]
