# Generated by Django 5.1.4 on 2025-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_remove_actividad_factura_actividad_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Asociado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto', verbose_name='Descripción de la Actividad'),
            preserve_default=False,
        ),
    ]
