# Generated by Django 5.1.4 on 2025-01-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_actividad_nombre_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
