# Generated by Django 5.1.4 on 2025-01-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_actividad_cantidad_actividad_equipo_actividad_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura'),
        ),
    ]
