# Generated by Django 5.1.4 on 2025-01-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_actividad_nombre_cliente_actividad_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('barrio', models.CharField(max_length=255, verbose_name='Barrio')),
                ('nombre_compania', models.CharField(max_length=255, verbose_name='Nombre de la Compañía')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado')], default='disponible', max_length=20, verbose_name='Estado del Pedido')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.categoria', verbose_name='Categoría')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.equipomaterial', verbose_name='Producto')),
            ],
        ),
    ]
