# Generated by Django 5.1.4 on 2025-01-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='producto',
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.factura', verbose_name='Factura asociada'),
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='poliza',
            field=models.BooleanField(default=False, verbose_name='¿Tiene póliza?'),
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='valor_factura_asociada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de la factura'),
        ),
    ]
