# Generated by Django 5.1.4 on 2025-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomaterial',
            name='fac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='fecha_salidas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salidas'),
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='poliza',
            field=models.BooleanField(default=False, verbose_name='¿Tiene póliza?'),
        ),
        migrations.AddField(
            model_name='equipomaterial',
            name='valor_factura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de la factura'),
        ),
    ]
