# Generated by Django 5.1.4 on 2025-01-17 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_equipomaterial_fac_equipomaterial_fecha_salidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Compra')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('referencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Referencia del equipo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del equipo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_entrada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('poliza', models.BooleanField(default=False, verbose_name='¿Tiene Póliza?')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.compra', verbose_name='Compra')),
            ],
        ),
    ]
