# Generated by Django 5.1.4 on 2025-01-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('tipo_reserva', models.CharField(choices=[('camara', 'Camara'), ('sonido', 'Sonido'), ('audiovisual', 'Audiovisual')], max_length=50, verbose_name='Tipo de Reserva')),
                ('descripcion_reserva', models.TextField(verbose_name='Descripción de la Reserva')),
                ('fecha_reserva', models.DateTimeField(verbose_name='Fecha de la Reserva')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
