# Generated by Django 5.1.4 on 2025-01-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Regreso de equipos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega de equipos'),
        ),
    ]
